AllCops:
  Include:
    - Rakefile
    - config.ru
  Exclude:
    - db/**/*
    - config/**/*
    - script/**/*
    - vendor/**/*
    - bin/**/*
    - node_modules/**/*

  RunRailsCops: true

Documentation:
  Enabled: false

Metrics/AbcSize:
  Enabled: false
